const {
  SPEC_DATA_SOURCE_CATALOG,
  SPEC_IMPLEMENTATION_NOTE,
  toResearchSeedSources,
} = require('../src/services/spec/specDataSourceCatalog');
const sourceLearning = require('../src/services/researchSourceLearningService');

describe('specDataSourceCatalog', () => {
  it('defines official SPEC source classes for PIT filings, macro, benchmarks, universe, and text research', () => {
    const ids = SPEC_DATA_SOURCE_CATALOG.map((source) => source.id);
    expect(ids).toEqual(expect.arrayContaining([
      'sec-edgar-submissions',
      'sec-data-api',
      'sec-current-13f-hr-atom',
      'sec-current-sc-13d-atom',
      'sec-current-sc-13g-atom',
      'nasdaq-symbol-directory',
      'bls-api',
      'bls-cpi-data-portal',
      'bls-cpi-average-price-data',
      'bls-ppi-data-portal',
      'bls-public-api-developers',
      'bls-public-api-v2-timeseries-data',
      'bea-api',
      'bea-itable',
      'fred-alfred-api',
      'fred-vehicle-total-sales',
      'fred-vehicle-light-sales',
      'fred-vehicle-domestic-auto-sales',
      'fred-nrs-new-one-family-houses-sold',
      'fred-nrs-median-sales-price',
      'fred-nrs-average-sales-price',
      'fred-nrs-new-one-family-houses-sold-nsa',
      'fred-nrs-new-houses-for-sale',
      'fred-nrs-months-supply-new-homes',
      'fred-nrc-total-building-permits',
      'fred-nrc-single-family-building-permits',
      'fred-nrc-total-housing-starts',
      'fred-nrc-single-family-housing-starts',
      'fred-nrc-housing-units-completed',
      'fred-nrc-housing-units-under-construction',
      'fred-nrc-core-construction-combined-csv',
      'treasury-fiscaldata-api',
      'census-economic-indicators',
      'census-timeseries-api-catalog',
      'census-manufacturers-shipments-inventories-orders-program',
      'census-manufacturers-shipments-inventories-orders-api',
      'census-advance-durable-goods-m3-api',
      'census-monthly-retail-trade-program',
      'census-monthly-retail-trade-api',
      'census-advance-monthly-retail-trade-api',
      'census-business-formation-statistics',
      'census-business-dynamics-statistics',
      'census-new-residential-sales',
      'census-new-residential-construction',
      'gdacs-home',
      'gdacs-api-docs',
      'gdacs-openapi-spec',
      'gdacs-rss-georss-feed-reference',
      'gdacs-rss-24h',
      'usgs-earthquake-catalog-docs',
      'usgs-earthquake-query-api',
      'usgs-earthquake-m45-30d-geojson-query',
      'usgs-earthquake-bbox-geojson-query-template',
      'usgs-earthquake-geojson-feeds',
      'usgs-earthquake-all-hour-geojson-feed',
      'usgs-earthquake-m25-day-geojson-feed',
      'usgs-earthquake-csv-feeds',
      'nasa-eonet-main',
      'nasa-eonet-api-docs-v3',
      'nasa-eonet-current-open-events',
      'nasa-eonet-recent-events-30d',
      'nasa-eonet-categories',
      'realtor-com-research-data-library',
      'redfin-data-center',
      'eia-open-data',
      'eia-api-v2',
      'eia-gasoline-diesel-fuel-update',
      'fama-french-data-library',
      'gdelt-global-news-events',
      'gdelt-doc-api',
      'google-news-rss-discovery',
      'sec-rss-directory',
      'sec-structured-disclosure-rss-feeds',
      'ftc-press-release-feed',
      'doj-justice-news-feed',
      'federal-reserve-press-feed',
      'cfpb-newsroom-feed',
      'fda-press-announcements',
      'defense-contracts-daily',
      'dod-contract-announcements-current-war-gov',
      'dod-contract-announcements-rss',
      'dod-contract-search-lockheed',
      'dod-contract-search-boeing',
      'dod-contract-search-palantir',
      'dod-contract-search-foreign',
      'sipri-databases-directory',
      'sipri-military-expenditure-database',
      'sipri-arms-transfers-database',
      'sipri-arms-transfers-sources-methods',
      'sipri-arms-industry-database',
      'sipri-financial-value-global-arms-trade',
      'sipri-arms-embargoes-database',
      'sipri-peace-operations-database-directory-entry',
      'sipri-nuclear-forces-directory-entry',
      'businesswire-issuer-press-release-discovery',
      'globenewswire-issuer-press-release-feeds',
      'prnewswire-issuer-press-release-feed',
      'amazon-best-sellers-all',
      'amazon-best-sellers-home-kitchen',
      'amazon-best-sellers-household-supplies',
      'amazon-best-sellers-kitchen-dining',
      'amazon-best-sellers-laundry-supplies',
      'amazon-best-sellers-cleaning-tools',
      'amazon-best-sellers-all-purpose-cleaners',
      'amazon-movers-and-shakers',
      'walmart-household-supply-bestsellers',
      'walmart-home-bestsellers',
      'walmart-top-100-home-trending',
      'walmart-cleaning-supplies-category',
      'walmart-cleaning-sponges-bestsellers',
      'noaa-nws-api',
      'nws-active-alerts-api',
      'nws-active-alerts-area-mo',
      'nws-active-alerts-point-st-louis',
      'nws-active-alerts-event-tornado-warning',
      'nrc-event-notification-reports',
      'nrc-event-notification-lastmonth-raw',
      'nrc-event-notification-data-dictionary',
      'nrc-power-reactor-status-reports',
      'nrc-power-reactor-status-last365-raw',
      'nrc-power-reactor-status-data-dictionary',
      'nifc-fire-information',
      'nifc-open-data-arcgis',
      'nifc-open-data-dcat-feed',
      'nifc-wfigs-current-interagency-fire-perimeters',
      'nifc-wfigs-current-perimeters-featureserver',
      'nifc-fire-history-services',
      'nifc-national-incident-map',
      'nifc-inciweb',
      'usdm-home',
      'usdm-data-downloads',
      'usdm-rest-web-service-info',
      'usdm-rest-us-area-percent-example',
      'usdm-rest-us-dsci-example',
      'usdm-gis-data',
      'openfema-api',
      'usaspending-api',
      'usaspending-api-endpoint-docs',
      'usaspending-advanced-award-search',
      'usaspending-search-spending-by-award-api',
      'usaspending-search-spending-by-award-count-api',
      'clinicaltrials-api-v2',
      'openfda-api',
      'openfda-food-enforcement-api',
      'usda-fsis-recalls-public-health-alerts',
      'usda-fsis-annual-recall-summaries',
      'usda-ers-weekly-retail-food-sales',
      'usda-ers-weekly-retail-food-sales-documentation',
      'usda-ams-market-news',
      'usda-ams-mymarketnews',
      'usda-ams-mymarketnews-api',
      'usda-ers-food-prices-expenditures-establishments',
      'usda-ers-food-price-outlook',
      'usda-ers-food-at-home-monthly-area-prices',
      'reliefweb-main',
      'reliefweb-api-docs',
      'reliefweb-endpoints-docs',
      'reliefweb-api-base-v1-requested',
      'reliefweb-api-base-v2',
      'reliefweb-disasters-api',
      'reliefweb-reports-api',
      'unhcr-refugee-data-finder',
      'unhcr-global-public-api',
      'unhcr-refugee-statistics-api-docs',
      'unhcr-population-api',
      'unhcr-countries-api',
      'unhcr-years-api',
      'unhcr-asylum-applications-api',
      'unhcr-asylum-decisions-api',
      'unhcr-demographics-api',
      'unhcr-solutions-api',
      'unhcr-idmc-api',
      'unhcr-unrwa-api',
      'emdat-main',
      'emdat-public-portal',
      'emdat-docs',
      'emdat-hdx-cred-organization',
      'emdat-hdx-package-search-api',
      'emdat-hdx-organization-api',
      'nhtsa-recalls-api',
      'nhtsa-recalls-by-vehicle-api',
      'nhtsa-recall-search',
      'cpsc-consumer-product-recalls-api',
      'cpsc-data-portal',
      'finviz-main',
      'finviz-screener',
      'finviz-screener-alternative',
      'finviz-top-gainers',
      'finviz-top-losers',
      'finviz-new-high',
      'finviz-new-low',
      'finviz-most-active',
      'finviz-unusual-volume',
      'finviz-analyst-upgrades',
      'finviz-analyst-downgrades',
      'finviz-insider-latest-buys',
      'finviz-quality-growth-fundamental-screen',
      'tradingview-stock-screener',
      'tradingview-us-stock-market',
      'tradingview-us-sectors',
      'tradingview-us-premarket-gainers',
      'tradingview-us-all-time-highs',
      'yahoo-finance-screener-hub',
      'yahoo-finance-equity-screener',
      'yahoo-finance-analyst-ratings-screener',
      'yahoo-finance-stock-gainers',
      'yahoo-finance-stock-losers',
      'yahoo-finance-most-active',
      'yahoo-finance-trending',
      'yahoo-finance-company-analysis',
      'yahoo-finance-company-financials',
      'yahoo-finance-company-cash-flow',
      'yahoo-finance-company-balance-sheet',
      'stockanalysis-household-personal-products-industry',
      'yahoo-finance-household-personal-products-industry',
      'companiesmarketcap-consumer-goods-revenue',
      'fortune-500-revenue-ranking',
      'nasdaq-main',
      'nasdaq-market-activity',
      'nasdaq-stocks',
      'nasdaq-earnings-calendar',
      'nasdaq-ipo-calendar',
      'nasdaq-company-analyst-research',
      'nasdaq-company-institutional-holdings',
      'nasdaq-company-insider-activity',
      'marketbeat-analyst-ratings',
      'marketbeat-analyst-upgrades',
      'marketbeat-analyst-downgrades',
      'marketbeat-price-target-changes',
      'marketbeat-consensus-forecast',
      'wallstreetzen-home',
      'wallstreetzen-stock-screener',
      'wallstreetzen-stock-ratings',
      'wallstreetzen-ticker-analysis',
      'finra-data-portal',
      'finra-fixed-income',
      'finra-corp-agency-bonds',
      'finra-corp-agency-trade-activity',
      'openalex-api',
    ]));
    expect(new Set(SPEC_DATA_SOURCE_CATALOG.map((source) => source.url)).size).toBe(SPEC_DATA_SOURCE_CATALOG.length);
    expect(SPEC_IMPLEMENTATION_NOTE).toMatch(/Do not invent APIs/);
  });

  it('converts SPEC sources into research seeds with required-field notes', () => {
    const seeds = toResearchSeedSources();
    const secSeed = seeds.find((seed) => seed.url.includes('sec.gov'));
    expect(secSeed.tags).toContain('spec');
    expect(secSeed.notes).toMatch(/Required SPEC fields/);
    expect(sourceLearning.SEED_SOURCES.some((source) => source.url === secSeed.url)).toBe(true);
    expect(sourceLearning.SEED_SOURCES.map((source) => source.url)).toEqual(expect.arrayContaining([
      'https://www.bloomberg.com/',
      'https://www.wsj.com/',
      'https://www.reuters.com/business/finance/',
      'https://finance.yahoo.com/',
      'https://www.cnbc.com/',
      'https://www.marketwatch.com/',
      'https://www.kiplinger.com/',
      'https://www.investopedia.com/',
      'https://www.economist.com/',
      'https://www.forbes.com/',
      'https://www.bls.gov/cpi/data.htm',
      'https://www.bls.gov/charts/consumer-price-index/consumer-price-index-average-price-data.htm',
      'https://www.bls.gov/ppi/data.htm',
      'https://www.bls.gov/developers/',
      'https://api.bls.gov/publicAPI/v2/timeseries/data/',
      'https://apps.bea.gov/api/',
      'https://apps.bea.gov/iTable/',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=TOTALSA',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=ALTSALES',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=DAUTOSAAR',
      'https://news.google.com/rss/search?q=business&hl=en-US&gl=US&ceid=US:en',
      'https://www.sec.gov/about/rss-feeds',
      'https://www.sec.gov/data-research/structured-data/structured-disclosure-rss-feeds',
      'https://www.ftc.gov/feeds/press-release.xml',
      'https://www.justice.gov/feeds/justice-news.xml',
      'https://www.federalreserve.gov/feeds/press_all.xml',
      'https://www.consumerfinance.gov/about-us/blog/feed/',
      'https://www.fda.gov/news-events/fda-newsroom/press-announcements',
      'https://www.defense.gov/News/Contracts/',
      'https://www.businesswire.com/portal/site/home/news/',
      'https://www.globenewswire.com/rss/list',
      'https://www.prnewswire.com/rss/',
      'https://www.weather.gov/documentation/services-web-api',
      'https://api.weather.gov/alerts/active',
      'https://api.weather.gov/alerts/active?area=MO',
      'https://api.weather.gov/alerts/active?point=38.6270,-90.1994',
      'https://api.weather.gov/alerts/active?event=Tornado%20Warning',
      'https://www.nrc.gov/reading-rm/doc-collections/event-status/event/',
      'https://www.nrc.gov/sites/default/files/doc_library/reading-rm/doc-collections/event-status/event/event-notification-rpt-lastmonth.txt',
      'https://www.nrc.gov/sites/default/files/doc_library/reading-rm/doc-collections/event-status/event/event-notification-rpt-datadictionary.xls',
      'https://www.nrc.gov/reading-rm/doc-collections/event-status/reactor-status/',
      'https://www.nrc.gov/reading-rm/doc-collections/event-status/reactor-status/PowerReactorStatusForLast365Days.txt',
      'https://www.nrc.gov/sites/default/files/doc_library/reading-rm/doc-collections/event-status/reactor-status/data_gov_powerstatus_datadictionary.xls',
      'https://www.nifc.gov/fire-information',
      'https://data-nifc.opendata.arcgis.com/',
      'https://data-nifc.opendata.arcgis.com/api/feed/dcat-us/1.1.json',
      'https://data-nifc.opendata.arcgis.com/datasets/nifc::wfigs-current-interagency-fire-perimeters/about',
      'https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/WFIGS_Interagency_Perimeters_Current/FeatureServer',
      'https://data-nifc.opendata.arcgis.com/pages/new_firehistory_services',
      'https://www.nifc.gov/nicc/incident-information/national-incident-map',
      'https://inciweb.wildfire.gov/',
      'https://droughtmonitor.unl.edu/',
      'https://droughtmonitor.unl.edu/DmData/DataDownload.aspx',
      'https://droughtmonitor.unl.edu/DmData/DataDownload/WebServiceInfo.aspx',
      'https://usdmdataservices.unl.edu/api/USStatistics/GetDroughtSeverityStatisticsByAreaPercent?aoi=us&startdate=7/1/2026&enddate=7/7/2026&statisticsType=1',
      'https://usdmdataservices.unl.edu/api/USStatistics/GetDSCI?aoi=us&startdate=7/1/2026&enddate=7/7/2026&statisticsType=1',
      'https://droughtmonitor.unl.edu/DmData/GISData.aspx',
      'https://api.census.gov/data/timeseries.html',
      'https://www.census.gov/manufacturing/m3/',
      'https://api.census.gov/data/timeseries/eits/m3',
      'https://api.census.gov/data/timeseries/eits/advm3',
      'https://www.census.gov/retail/',
      'https://api.census.gov/data/timeseries/eits/mrts',
      'https://api.census.gov/data/timeseries/eits/mrts.html',
      'https://api.census.gov/data/timeseries/eits/mrts/variables.html',
      'https://api.census.gov/data/timeseries/eits/mrts/examples.html',
      'https://api.census.gov/data/timeseries/eits/marts',
      'https://api.census.gov/data/timeseries/eits/marts.html',
      'https://api.census.gov/data/timeseries/eits/marts/variables.html',
      'https://www.census.gov/mtis/',
      'https://api.census.gov/data/timeseries/eits/mtis',
      'https://api.census.gov/data/timeseries/eits/mtis.html',
      'https://api.census.gov/data/timeseries/eits/mtis/variables.html',
      'https://www.census.gov/programs-surveys/arts.html',
      'https://www.census.gov/construction/nrs/',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=HSN1F',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=MSPNHSUS',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=ASPNHSUS',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=HSN1FNSA',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=HNFSEPUSSA',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=MSACSR',
      'https://www.census.gov/construction/nrc/',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=PERMIT',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=PERMIT1',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=HOUST',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=HOUST1F',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=COMPUTSA',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=UNDCONTSA',
      'https://fred.stlouisfed.org/graph/fredgraph.csv?id=PERMIT,HOUST,COMPUTSA,UNDCONTSA',
      'https://www.realtor.com/research/data/',
      'https://www.redfin.com/news/data-center/',
      'https://www.gdacs.org/',
      'https://www.gdacs.org/gdacsapi/swagger/index.html',
      'https://www.gdacs.org/gdacsapi/swagger/v1/swagger.json',
      'https://www.gdacs.org/feed_reference.aspx',
      'https://www.gdacs.org/xml/rss_24h.xml',
      'https://earthquake.usgs.gov/fdsnws/event/1/',
      'https://earthquake.usgs.gov/fdsnws/event/1/query',
      'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=now-30days&minmagnitude=4.5',
      'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&minlatitude=24&maxlatitude=50&minlongitude=-125&maxlongitude=-66&starttime=2026-01-01',
      'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php',
      'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson',
      'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson',
      'https://earthquake.usgs.gov/earthquakes/feed/v1.0/csv.php',
      'https://eonet.gsfc.nasa.gov/',
      'https://eonet.gsfc.nasa.gov/docs/v3',
      'https://eonet.gsfc.nasa.gov/api/v3/events?status=open',
      'https://eonet.gsfc.nasa.gov/api/v3/events?days=30',
      'https://eonet.gsfc.nasa.gov/api/v3/categories',
      'https://www.eia.gov/opendata/',
      'https://api.eia.gov/v2/',
      'https://www.eia.gov/petroleum/gasdiesel/',
      'https://api.fda.gov/food/enforcement.json',
      'https://www.fsis.usda.gov/recalls',
      'https://www.fsis.usda.gov/food-safety/recalls-public-health-alerts/annual-recall-summaries',
      'https://www.ers.usda.gov/data-products/weekly-retail-food-sales',
      'https://www.ers.usda.gov/data-products/weekly-retail-food-sales/documentation',
      'https://www.ams.usda.gov/market-news',
      'https://mymarketnews.ams.usda.gov/',
      'https://mymarketnews.ams.usda.gov/mymarketnews-api',
      'https://www.ers.usda.gov/topics/food-markets-prices/food-prices-expenditures-and-establishments',
      'https://www.ers.usda.gov/data-products/food-price-outlook',
      'https://www.ers.usda.gov/data-products/food-at-home-monthly-area-prices',
      'https://reliefweb.int/',
      'https://apidoc.reliefweb.int/',
      'https://apidoc.reliefweb.int/endpoints',
      'https://api.reliefweb.int/v1/',
      'https://api.reliefweb.int/v2/',
      'https://api.reliefweb.int/v2/disasters?appname=your-application',
      'https://api.reliefweb.int/v2/reports?appname=your-application',
      'https://www.unhcr.org/refugee-statistics/',
      'https://api.unhcr.org/',
      'https://api.unhcr.org/docs/refugee-statistics.html',
      'https://api.unhcr.org/population/v1/population/',
      'https://api.unhcr.org/population/v1/countries/',
      'https://api.unhcr.org/population/v1/years/',
      'https://api.unhcr.org/population/v1/asylum-applications/',
      'https://api.unhcr.org/population/v1/asylum-decisions/',
      'https://api.unhcr.org/population/v1/demographics/',
      'https://api.unhcr.org/population/v1/solutions/',
      'https://api.unhcr.org/population/v1/idmc/',
      'https://api.unhcr.org/population/v1/unrwa/',
      'https://www.emdat.be/',
      'https://public.emdat.be/',
      'https://doc.emdat.be/',
      'https://data.humdata.org/organization/cred',
      'https://data.humdata.org/api/3/action/package_search?fq=organization:cred&q=EM-DAT&rows=25',
      'https://data.humdata.org/api/3/action/organization_show?id=cred&include_datasets=true',
      'https://www.nhtsa.gov/nhtsa-datasets-and-apis',
      'https://api.nhtsa.gov/recalls/recallsByVehicle?make=Ford&model=F-150&modelYear=2024',
      'https://www.nhtsa.gov/recalls',
      'https://www.saferproducts.gov/RestWebServices/Recall?format=json',
      'https://www.cpsc.gov/Data',
      'https://www.amazon.com/Best-Sellers/zgbs',
      'https://www.amazon.com/Best-Sellers-Home-Kitchen/zgbs/home-garden',
      'https://www.amazon.com/Best-Sellers-Household-Supplies/zgbs/hpc/15342811',
      'https://www.amazon.com/Best-Sellers-Kitchen-Dining/zgbs/kitchen',
      'https://www.amazon.com/Best-Sellers-Laundry-Supplies/zgbs/hpc/15356111',
      'https://www.amazon.com/Best-Sellers-Household-Cleaning-Tools/zgbs/hpc/15342831',
      'https://www.amazon.com/Best-Sellers-All-Purpose-Household-Cleaners/zgbs/hpc/15356141',
      'https://www.amazon.com/gp/movers-and-shakers',
      'https://www.walmart.com/c/best-sellers/household-supplies',
      'https://www.walmart.com/shop/best-sellers/home',
      'https://www.walmart.com/shop/top-100-home-trending',
      'https://www.walmart.com/browse/household-essentials/cleaning-supplies/1115193_1071966',
      'https://www.walmart.com/c/best-sellers/household-cleaning-sponges',
      'https://finviz.com/',
      'https://finviz.com/screener.ashx',
      'https://finviz.com/screener',
      'https://finviz.com/screener.ashx?v=111&s=ta_topgainers',
      'https://finviz.com/screener.ashx?v=111&s=ta_toplosers',
      'https://finviz.com/screener.ashx?v=111&s=ta_newhigh',
      'https://finviz.com/screener.ashx?v=111&s=ta_newlow',
      'https://finviz.com/screener.ashx?v=111&s=ta_mostactive',
      'https://finviz.com/screener.ashx?v=111&s=ta_unusualvolume',
      'https://finviz.com/screener.ashx?v=111&s=n_upgrades',
      'https://finviz.com/screener.ashx?v=111&s=n_downgrades',
      'https://finviz.com/screener.ashx?v=111&s=it_latestbuys',
      'https://finviz.com/screener.ashx?v=111&f=cap_midover,fa_debteq_u1,fa_roe_o15,fa_sales5years_pos,sh_avgv',
      'https://www.tradingview.com/screener/',
      'https://www.tradingview.com/markets/stocks-usa/',
      'https://www.tradingview.com/markets/stocks-usa/sectorandindustry-sector/',
      'https://www.tradingview.com/markets/stocks-usa/market-movers-pre-market-gainers/',
      'https://www.tradingview.com/markets/stocks-usa/market-movers-ath/',
      'https://finance.yahoo.com/research-hub/screener/',
      'https://finance.yahoo.com/research-hub/screener/equity/',
      'https://finance.yahoo.com/research-hub/screener/analyst_ratings/',
      'https://finance.yahoo.com/markets/stocks/gainers/',
      'https://finance.yahoo.com/markets/stocks/losers/',
      'https://finance.yahoo.com/markets/stocks/most-active/',
      'https://finance.yahoo.com/markets/stocks/trending/',
      'https://finance.yahoo.com/quote/{ticker}/analysis/',
      'https://finance.yahoo.com/quote/{ticker}/financials/',
      'https://finance.yahoo.com/quote/{ticker}/cash-flow/',
      'https://finance.yahoo.com/quote/{ticker}/balance-sheet/',
      'https://stockanalysis.com/stocks/industry/household-and-personal-products/',
      'https://finance.yahoo.com/sectors/consumer-defensive/household-personal-products/',
      'https://companiesmarketcap.com/consumer-goods/largest-consumer-goods-companies-by-revenue/',
      'https://fortune.com/ranking/fortune500/',
      'https://www.nasdaq.com/',
      'https://www.nasdaq.com/market-activity',
      'https://www.nasdaq.com/market-activity/stocks',
      'https://www.nasdaq.com/market-activity/earnings',
      'https://www.nasdaq.com/market-activity/ipos',
      'https://www.nasdaq.com/market-activity/stocks/{ticker}/analyst-research',
      'https://www.nasdaq.com/market-activity/stocks/{ticker}/institutional-holdings',
      'https://www.nasdaq.com/market-activity/stocks/{ticker}/insider-activity',
      'https://www.marketbeat.com/ratings/',
      'https://www.marketbeat.com/ratings/upgrades/',
      'https://www.marketbeat.com/ratings/downgrades/',
      'https://www.marketbeat.com/ratings/price-target-changes/',
      'https://www.marketbeat.com/stocks/NASDAQ/{ticker}/forecast/',
      'https://www.wallstreetzen.com/',
      'https://www.wallstreetzen.com/stock-screener',
      'https://www.wallstreetzen.com/stock-ratings',
      'https://www.wallstreetzen.com/stocks/us/{exchange}/{ticker}',
      'https://www.finra.org/finra-data',
      'https://www.finra.org/finra-data/fixed-income',
      'https://www.finra.org/finra-data/fixed-income/corp-and-agency',
      'https://www.finra.org/finra-data/fixed-income/corp-and-agency/trade',
      'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=13F-HR&count=100&output=atom',
      'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=SC%2013D&count=100&output=atom',
      'https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=SC%2013G&count=100&output=atom',
    ]));
    expect(sourceLearning.scoreText('SEC EDGAR XBRL filing acceptance timestamp companyfacts benchmark')).toBeGreaterThan(3);
    expect(sourceLearning.scoreText('GDELT weather disaster clinical trial openFDA federal contract recall local risk')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('National Weather Service NWS active alerts Tornado Warning area point event severity urgency certainty watches warnings advisories identifying User-Agent')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('NRC Event Notification Reports power reactor status nuclear facility event Part 21 emergency class CFR code reactor scram shutdown current power derate outage')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('NIFC WFIGS current wildfire perimeters acres burned containment IRWIN incident status preparedness level InciWeb fire history FeatureServer GeoJSON')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('U.S. Drought Monitor USDM DSCI D0 D1 D2 D3 D4 drought severity area percent county HUC GeoJSON agriculture water utility food inflation')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('FINRA fixed income corporate bond trade activity yield spread widening falling bond prices distressed trading downgrade risk refinancing pressure equity credit divergence')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('SEC 13F-HR institutional holdings hedge fund positions Schedule 13D activist stake Schedule 13G beneficial ownership position reductions concentrated ownership')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('GDACS Global Disaster Alert Coordination System RSS GeoRSS earthquake tropical cyclone flood wildfire drought volcano tsunami alert level population exposure geometry cross border disaster monitoring')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('TradingView stock screener pre-market gainers all time highs sector leadership relative strength market movers volume anomalies')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Yahoo Finance equity screener analyst ratings stock gainers losers most active trending quote analysis financials cash flow balance sheet')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Stock Analysis household personal products industry CompaniesMarketCap consumer goods revenue ranking Fortune 500 market cap profit valuation dividend yield CPG consumer defensive')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Nasdaq market activity stocks earnings calendar IPO calendar analyst research institutional holdings insider activity market reports')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('MarketBeat analyst recommendations upgrades downgrades price target changes broker actions previous rating new rating previous target new target consensus forecast')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('WallStreetZen stock screener Zen Ratings quantitative ratings value growth momentum sentiment safety financials AI component grades fair value price ticker analysis')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('USGS Earthquake Catalog API FDSN GeoJSON magnitude depth PAGER alert MMI CDI tsunami ShakeMap real-time feeds seismic risk supply chain')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('NASA EONET Earth Observatory Natural Event Tracker current open events wildfires severe storms volcanoes floods drought dust haze landslides extreme temperatures satellite imagery geometry magnitude source URLs')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('SEC RSS trading suspension FTC DOJ antitrust FDA approval defense contract catalyst')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('BLS CPI consumer price index inflation average price data eggs milk bread meat gasoline electricity natural gas CUUR0000SA0 APU0000708111 seriesid')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('BLS PPI Producer Price Index selling prices domestic producers final demand intermediate demand manufacturer pricing input cost pressure wholesale price trends industry margins price pass-through')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('BEA API iTable FRED TOTALSA ALTSALES DAUTOSAAR vehicle sales light vehicle sales domestic auto sales aggregate sales SAAR auto demand')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('issuer-paid GlobeNewswire PR Newswire Business Wire product launch partnership earnings verification required')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Census New Residential Sales new home sales months supply median average sales price financing type homebuilders')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('FRED CSV HSN1F MSPNHSUS ASPNHSUS HSN1FNSA HNFSEPUSSA MSACSR new houses for sale months supply')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Census New Residential Construction PERMIT HOUST COMPUTSA UNDCONTSA building permits housing starts units under construction completions')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('EIA API v2 gasoline prices diesel prices petroleum product supplied retail fuel volumes refinery output inventories electricity sales prices natural gas sales prices shipping logistics costs')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('EIA Gasoline and Diesel Fuel Update weekly retail fuel prices dollars per gallon PADD state city full history XLS consumer fuel pressure')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Census M3 ADVM3 manufacturers shipments inventories orders new orders unfilled orders durable goods computers electronics machinery transportation equipment upstream demand')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Census MRTS MARTS monthly retail trade retail sales inventory inventory-to-sales category_code data_type_code nonstore ecommerce general merchandise gasoline clothing motor vehicle parts')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Census MTIS Manufacturing and Trade Inventories and Sales retail wholesale manufacturing sales inventories inventory-to-sales demand slowdown excess inventory supply shortage')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Census ARTS Annual Retail Trade Survey AIES annual retail sales e-commerce inventories gross margins operating expenses merchandise line NAICS restatement employer-only')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Realtor.com median listing price active listing count pending listings market hotness ZIP code listing market not completed sale price')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Redfin Data Center homes sold pending sales median sale price sale-to-list ratio percent sold above list ZIP city county metro')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('CPSC consumer product recalls API manufacturer retailer hazard injury remedy affected units fire risk refund replacement')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('openFDA food enforcement recall reports recalling firm product description classification distribution pattern product quantity reason for recall')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('USDA FSIS meat poultry egg recalls establishment number pounds recalled geographic distribution recall classification health risk retail distribution list')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('USDA ERS Weekly Retail Food Sales Circana scanner data grocery demand food category sales unit sales price-versus-volume pandemic recession seasonal demand public summary proprietary UPC')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('USDA AMS Market News MyMarketNews agricultural commodity prices sales volume beef pork poultry dairy eggs grains fruits vegetables specialty crops livestock wholesale retail shipping data')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('USDA ERS Food Price Outlook food CPI PPI forecasts food prices expenditures establishments F-MAP food-at-home monthly area prices farm-to-retail price spreads mean unit value')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('ReliefWeb humanitarian reports disasters casualty displacement aid requirements situation reports conflict emergencies government NGO response appname source organizations')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('UNHCR Refugee Data Finder refugees asylum seekers IDPs stateless country of origin host country trends demographics solutions population v1 API')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('EM-DAT CRED historical disaster database country disaster type subtype economic losses deaths injuries affected displaced international assistance HDX package search')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('NHTSA recallsByVehicle API manufacturer campaign number vehicles potentially affected component defect description consequence remedy completion analysis brand quality trends')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Amazon Best Sellers Movers and Shakers household supplies kitchen dining laundry cleaning tools all purpose cleaners bestseller rank sales rank acceleration product demand ecommerce storefront rank')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('Walmart Best Sellers top 100 home trending household supplies cleaning sponges bought since yesterday low stock availability unit price review count rating demand proxy')).toBeGreaterThan(6);
    expect(sourceLearning.scoreText('FINVIZ stock screener top gainers unusual volume analyst upgrades latest insider buys valuation growth profitability ROE debt equity sales growth delayed quotes')).toBeGreaterThan(6);
  });
});
