const SPEC_IMPLEMENTATION_NOTE = [
  'Do not invent APIs, data fields, or library behavior.',
  'Consult official documentation before implementing an external integration.',
  'When source behavior is uncertain, isolate it behind an interface, add tests, and avoid silent assumptions.',
].join(' ');

const SPEC_DATA_SOURCE_CATALOG = [
  {
    id: 'sec-edgar-submissions',
    url: 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces',
    title: 'SEC EDGAR submissions and XBRL APIs',
    category: 'filings',
    tags: ['spec', 'sec', 'edgar', 'filings', 'xbrl', 'fundamentals', 'point-in-time'],
    credibilityScore: 96,
    relevanceScore: 92,
    requiredFields: ['SEC filing acceptance timestamp', 'fundamental reporting period', 'fundamental publication timestamp', 'revision version'],
    implementationNotes: 'Use official SEC documentation and fair-access guidance before adding any adapter. Store raw submissions/XBRL immutably before normalized fundamentals.',
  },
  {
    id: 'sec-data-api',
    url: 'https://data.sec.gov/',
    title: 'SEC data.sec.gov API landing page',
    category: 'filings',
    tags: ['spec', 'sec', 'companyfacts', 'submissions', 'xbrl', 'raw-source'],
    credibilityScore: 96,
    relevanceScore: 90,
    requiredFields: ['SEC filing acceptance timestamp', 'data source', 'ingestion timestamp'],
    implementationNotes: 'Official JSON endpoints for submissions and extracted XBRL. Adapter must provide a descriptive User-Agent and rate-limit per SEC fair-access policy.',
  },
  {
    id: 'nasdaq-symbol-directory',
    url: 'https://www.nasdaqtrader.com/trader.aspx?id=symboldirdefs',
    title: 'Nasdaq Trader Symbol Directory definitions',
    category: 'security-master',
    tags: ['spec', 'universe', 'symbol-directory', 'listing', 'etf', 'security-master'],
    credibilityScore: 88,
    relevanceScore: 86,
    requiredFields: ['symbol', 'exchange', 'security type', 'listing status'],
    implementationNotes: 'Use as a curated security-master seed only. Historical universes still need PIT snapshots and delisting retention.',
  },
  {
    id: 'nasdaq-listed-symbols',
    url: 'https://www.nasdaqtrader.com/dynamic/symdir/nasdaqlisted.txt',
    title: 'Nasdaq-listed securities text file',
    category: 'security-master',
    tags: ['spec', 'universe', 'nasdaq-listed', 'listing', 'security-master'],
    credibilityScore: 86,
    relevanceScore: 84,
    requiredFields: ['symbol', 'security name', 'ETF flag', 'test issue flag'],
    implementationNotes: 'Use only through a tested parser. Do not treat current symbol lists as historical universe membership.',
  },
  {
    id: 'bls-api',
    url: 'https://www.bls.gov/bls/api_features.htm',
    title: 'BLS Public Data API',
    category: 'macro',
    tags: ['spec', 'macro', 'labor', 'inflation', 'release-timestamp', 'data-api'],
    credibilityScore: 92,
    relevanceScore: 86,
    requiredFields: ['macro release timestamp', 'data source', 'revision version'],
    implementationNotes: 'Use BLS official API signatures for CPI, employment, wages, and labor data. Preserve publication/release timestamps when available.',
  },
  {
    id: 'bea-api',
    url: 'https://www.bea.gov/resources/for-developers',
    title: 'BEA developer resources and API',
    category: 'macro',
    tags: ['spec', 'macro', 'gdp', 'income', 'consumer', 'bea-api'],
    credibilityScore: 92,
    relevanceScore: 86,
    requiredFields: ['macro release timestamp', 'revision version', 'data source'],
    implementationNotes: 'Use official BEA metadata endpoints before mapping datasets. BEA API keys must remain in credentials/config only.',
  },
  {
    id: 'fred-alfred-api',
    url: 'https://fred.stlouisfed.org/docs/api/fred/',
    title: 'FRED and ALFRED API documentation',
    category: 'macro',
    tags: ['spec', 'macro', 'alfred', 'fred', 'vintages', 'rates', 'point-in-time'],
    credibilityScore: 94,
    relevanceScore: 90,
    requiredFields: ['macro release timestamp', 'revision version', 'data source'],
    implementationNotes: 'Prefer ALFRED vintages for point-in-time macro where possible. Do not use revised FRED values as if they were available historically.',
  },
  {
    id: 'federal-reserve-h15',
    url: 'https://www.federalreserve.gov/releases/h15/',
    title: 'Federal Reserve H.15 Selected Interest Rates',
    category: 'rates',
    tags: ['spec', 'treasury', 'rates', 'yield-curve', 'benchmark', 'h15'],
    credibilityScore: 93,
    relevanceScore: 86,
    requiredFields: ['macro release timestamp', 'Treasury-bill return', 'yield-curve slope'],
    implementationNotes: 'Use the Federal Reserve Data Download Program or FRED/ALFRED vintages; preserve release dates and avoid look-ahead revised data.',
  },
  {
    id: 'treasury-fiscaldata-api',
    url: 'https://fiscaldata.treasury.gov/api-documentation/',
    title: 'U.S. Treasury FiscalData API documentation',
    category: 'rates',
    tags: ['spec', 'treasury', 'fiscaldata', 't-bill', 'cash-benchmark'],
    credibilityScore: 92,
    relevanceScore: 84,
    requiredFields: ['Treasury-bill return', 'data source', 'ingestion timestamp'],
    implementationNotes: 'Use official FiscalData APIs for Treasury datasets and cash/rate benchmark support.',
  },
  {
    id: 'census-economic-indicators',
    url: 'https://www.census.gov/data/developers/data-sets/economic-indicators.html',
    title: 'Census Economic Indicators API datasets',
    category: 'consumer',
    tags: ['spec', 'consumer', 'retail-sales', 'economic-indicators', 'census-api'],
    credibilityScore: 90,
    relevanceScore: 84,
    requiredFields: ['macro release timestamp', 'consumer sales reports', 'revision version'],
    implementationNotes: 'Use official Census API guidance for retail, trade, housing, and manufacturing indicator time series.',
  },
  {
    id: 'census-business-formation-statistics',
    url: 'https://www.census.gov/econ/bfs/index.html',
    title: 'Census Business Formation Statistics',
    category: 'business-formation',
    tags: ['spec', 'census', 'bfs', 'business-formation', 'ein-applications', 'startup-formation', 'economic-indicators'],
    credibilityScore: 91,
    relevanceScore: 86,
    requiredFields: ['time period', 'category code', 'data type code', 'seasonal adjustment flag', 'aggregate value', 'API key/configuration status'],
    implementationNotes: 'Use the official BFS API variable listing before selecting fields. Treat BFS as aggregate formation momentum, not a named-company discovery source.',
  },
  {
    id: 'census-business-dynamics-statistics',
    url: 'https://www.census.gov/programs-surveys/bds/data.html',
    title: 'Census Business Dynamics Statistics',
    category: 'business-dynamics',
    tags: ['spec', 'census', 'bds', 'business-dynamics', 'firm-startups', 'establishment-births', 'establishment-deaths', 'firm-shutdowns', 'job-creation', 'job-destruction'],
    credibilityScore: 91,
    relevanceScore: 86,
    requiredFields: ['year', 'geography', 'firm startups/firms', 'establishment births', 'establishment deaths', 'firm shutdowns', 'job creation', 'job destruction', 'API key/configuration status'],
    implementationNotes: 'Use the official BDS API variable listing before selecting fields. Treat BDS as annual aggregate business-dynamism context and never as a named-new-company discovery source.',
  },
  {
    id: 'eia-open-data',
    url: 'https://www.eia.gov/opendata/documentation.php',
    title: 'EIA Open Data API documentation',
    category: 'commodities',
    tags: ['spec', 'energy', 'oil', 'gas', 'commodities', 'shipping-costs'],
    credibilityScore: 90,
    relevanceScore: 84,
    requiredFields: ['commodity trend', 'macro release timestamp', 'data source'],
    implementationNotes: 'Use official EIA Open Data endpoints for oil/gas/electricity inputs that affect energy, logistics, and shipping-cost evaluation.',
  },
  {
    id: 'fama-french-data-library',
    url: 'https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html',
    title: 'Kenneth French Data Library',
    category: 'factor-benchmark',
    tags: ['spec', 'factor-benchmark', 'market-factor', 'size', 'value', 'momentum'],
    credibilityScore: 88,
    relevanceScore: 82,
    requiredFields: ['relevant factor benchmarks', 'benchmark performance', 'data source'],
    implementationNotes: 'Use as benchmark/factor reference data, not as a security-master replacement. Record exact file vintage when ingested.',
  },
  {
    id: 'world-bank-open-data',
    url: 'https://data.worldbank.org/',
    title: 'World Bank Open Data',
    category: 'global-macro',
    tags: ['spec', 'global', 'population', 'gdp', 'macro', 'demand'],
    credibilityScore: 88,
    relevanceScore: 80,
    requiredFields: ['population data', 'GDP trend', 'data source'],
    implementationNotes: 'Use for global demand/population/GDP context. Keep publication/available-at assumptions explicit in adapter tests.',
  },
  {
    id: 'news-source-ratings',
    url: 'https://yougov.com/en-us/ratings/news-websites',
    title: 'YouGov news website ratings seed',
    category: 'news-source-quality',
    tags: ['spec', 'news', 'source-quality', 'text-derived', 'low-confidence-social'],
    credibilityScore: 62,
    relevanceScore: 66,
    requiredFields: ['document references', 'citations', 'source quality'],
    implementationNotes: 'Use only for discovery/source-quality context. Text claims still require document citations and prompt-injection screening.',
  },
  {
    id: 'gdelt-global-news-events',
    url: 'https://www.gdeltproject.org/',
    title: 'GDELT global news, events, locations, organizations, and tone',
    category: 'global-news-events',
    tags: ['spec', 'news', 'events', 'war', 'geopolitics', 'location-aware', 'sentiment', 'organizations'],
    credibilityScore: 82,
    relevanceScore: 90,
    requiredFields: ['event timestamp', 'article/document reference', 'location', 'organization/entity', 'tone/sentiment', 'source language'],
    implementationNotes: 'Use GDELT DOC/GEO/Event/GKG APIs as global, near-real-time context for war, civil unrest, local demand, supply-chain disruption, organization mentions, and narrative tone. Treat it as text/event evidence that must be tied to company geography before changing scores.',
  },
  {
    id: 'gdelt-doc-api',
    url: 'https://api.gdeltproject.org/api/v2/doc/doc',
    title: 'GDELT DOC 2.0 full-text global news search API',
    category: 'global-business-news-search',
    tags: ['spec', 'gdelt', 'doc-api', 'business-news', 'startup', 'funding', 'ipo', 'acquisition', 'global-news', 'no-login'],
    credibilityScore: 84,
    relevanceScore: 92,
    requiredFields: ['query', 'article URL', 'article title', 'seen date', 'domain/source', 'source country', 'language', 'tone when provided'],
    implementationNotes: 'Use public DOC 2.0 artlist JSON queries for broad business, new-company, funding, IPO, and acquisition discovery. Treat article text as untrusted evidence and expand ticker/company implications through the existing crawl/Finnhub/company-discovery pipeline.',
  },
  {
    id: 'google-news-rss-discovery',
    url: 'https://news.google.com/rss/search?q=business&hl=en-US&gl=US&ceid=US:en',
    title: 'Google News RSS business discovery feeds',
    category: 'business-news-discovery',
    tags: ['spec', 'news', 'google-news', 'rss', 'business-news', 'startup', 'funding', 'ipo', 'discovery', 'undocumented'],
    credibilityScore: 66,
    relevanceScore: 86,
    requiredFields: ['feed query', 'article URL', 'article title', 'publication timestamp', 'publisher/source', 'discovery timestamp'],
    implementationNotes: 'Use Google News RSS only as an undocumented aggregation/discovery interface for business, new-company, startup-funding, IPO, and topic feeds. Do not treat availability, ranking, or schema behavior as guaranteed production API behavior; crawl cited publishers for primary evidence.',
  },
  {
    id: 'sec-rss-directory',
    url: 'https://www.sec.gov/about/rss-feeds',
    title: 'SEC news, enforcement, and EDGAR RSS directory',
    category: 'regulatory-news',
    tags: ['spec', 'sec', 'rss', 'press-release', 'litigation-release', 'administrative-proceeding', 'trading-suspension', 'edgar-filings', 'regulatory-risk'],
    credibilityScore: 95,
    relevanceScore: 90,
    requiredFields: ['SEC source feed', 'material date', 'company/entity mention', 'filing or release URL', 'ingestion timestamp'],
    implementationNotes: 'Use the official SEC RSS directory to keep current with press releases, speeches/statements, litigation releases, administrative proceedings, trading suspensions, and EDGAR filing feeds. Enforcement items should increase regulatory-risk review rather than directly force trades.',
  },
  {
    id: 'sec-structured-disclosure-rss-feeds',
    url: 'https://www.sec.gov/data-research/structured-data/structured-disclosure-rss-feeds',
    title: 'SEC structured disclosure RSS feeds',
    category: 'structured-filings',
    tags: ['spec', 'sec', 'rss', 'structured-disclosure', 'xbrl', 'inline-xbrl', 'edgar-filings', 'fundamentals'],
    credibilityScore: 96,
    relevanceScore: 91,
    requiredFields: ['company name', 'CIK', 'accession number', 'form type', 'filing date', 'EDGAR URL', 'structured data package URL'],
    implementationNotes: 'Use official structured disclosure RSS feeds for current XBRL/Inline XBRL filings. The SEC states these feeds update every ten minutes during the weekday operating window; preserve filing dates and accession numbers before scoring fundamentals.',
  },
  {
    id: 'ftc-press-release-feed',
    url: 'https://www.ftc.gov/feeds/press-release.xml',
    title: 'FTC press releases RSS',
    category: 'regulatory-news',
    tags: ['spec', 'ftc', 'rss', 'antitrust', 'consumer-protection', 'merger', 'competition', 'enforcement'],
    credibilityScore: 92,
    relevanceScore: 84,
    requiredFields: ['release date', 'company/entity mention', 'topic', 'release URL', 'enforcement or merger context'],
    implementationNotes: 'Use for mergers, antitrust actions, competition policy, consumer-protection cases, settlements, and enforcement risk. Tie company mentions to public tickers before candidate scoring.',
  },
  {
    id: 'doj-justice-news-feed',
    url: 'https://www.justice.gov/feeds/justice-news.xml',
    title: 'Department of Justice all-news RSS',
    category: 'regulatory-news',
    tags: ['spec', 'doj', 'rss', 'antitrust', 'fraud', 'corporate-crime', 'settlement', 'enforcement'],
    credibilityScore: 92,
    relevanceScore: 83,
    requiredFields: ['release date', 'component', 'company/entity mention', 'topic', 'news URL'],
    implementationNotes: 'Use the current DOJ all-news RSS for antitrust, fraud, corporate criminal cases, settlements, and enforcement. The older OPA feed path can 404, so adapters should prefer this verified feed and fall back to the DOJ news page/API where needed.',
  },
  {
    id: 'federal-reserve-press-feed',
    url: 'https://www.federalreserve.gov/feeds/press_all.xml',
    title: 'Federal Reserve press-release RSS',
    category: 'macro-policy-news',
    tags: ['spec', 'federal-reserve', 'rss', 'monetary-policy', 'interest-rates', 'macro', 'banking'],
    credibilityScore: 94,
    relevanceScore: 88,
    requiredFields: ['release timestamp', 'release category', 'policy topic', 'URL', 'market-impact context'],
    implementationNotes: 'Use for current monetary-policy, banking, supervision, and macro-policy announcements. Keep it separate from historical rate series so narrative policy shocks can be evaluated against point-in-time market data.',
  },
  {
    id: 'cfpb-newsroom-feed',
    url: 'https://www.consumerfinance.gov/about-us/blog/feed/',
    title: 'Consumer Financial Protection Bureau newsroom feed',
    category: 'consumer-finance-regulatory-news',
    tags: ['spec', 'cfpb', 'rss', 'consumer-finance', 'banking', 'credit', 'enforcement', 'regulatory-risk'],
    credibilityScore: 90,
    relevanceScore: 80,
    requiredFields: ['publication date', 'company/entity mention', 'consumer-finance topic', 'URL', 'enforcement or policy context'],
    implementationNotes: 'Use for consumer-finance policy, enforcement, banking, credit, mortgage, and fintech regulatory-risk context. Connect affected business lines and geography before scoring a company.',
  },
  {
    id: 'fda-press-announcements',
    url: 'https://www.fda.gov/news-events/fda-newsroom/press-announcements',
    title: 'FDA press announcements and press-release feed',
    category: 'healthcare-regulatory-news',
    tags: ['spec', 'fda', 'rss', 'press-announcement', 'drug-approval', 'medical-device', 'recall', 'safety-warning', 'healthcare-catalyst'],
    credibilityScore: 92,
    relevanceScore: 84,
    requiredFields: ['announcement date', 'product/company mention', 'regulatory action', 'announcement URL', 'approval/recall/safety context'],
    implementationNotes: 'Use the FDA press announcements page and official press-release RSS for drug approvals, medical-device decisions, recalls, safety warnings, and healthcare catalysts. Pair with openFDA/ClinicalTrials evidence before scoring biotech or device companies.',
  },
  {
    id: 'defense-contracts-daily',
    url: 'https://www.defense.gov/News/Contracts/',
    title: 'Department of Defense daily contract announcements',
    category: 'government-contracts',
    tags: ['spec', 'department-of-defense', 'defense-contracts', 'government-contracts', 'aerospace', 'military', 'revenue-catalyst'],
    credibilityScore: 92,
    relevanceScore: 86,
    requiredFields: ['award date', 'contractor', 'award amount', 'service/agency', 'location', 'contract URL'],
    implementationNotes: 'Use daily DoD contract announcements and the DoD contracts RSS feed to identify revenue catalysts for defense, aerospace, logistics, software, and industrial suppliers. Validate contractor/ticker mappings before trade scoring.',
  },
  {
    id: 'noaa-nws-api',
    url: 'https://www.weather.gov/documentation/services-web-api',
    title: 'NOAA/National Weather Service API',
    category: 'weather-hazards',
    tags: ['spec', 'weather', 'alerts', 'local-risk', 'supply-chain', 'retail-footprint', 'location-aware'],
    credibilityScore: 93,
    relevanceScore: 82,
    requiredFields: ['alert effective timestamp', 'alert area', 'severity', 'certainty', 'urgency', 'company location overlap'],
    implementationNotes: 'Use for U.S. weather alerts, forecasts, observations, and localized operational risk. Official requests require a unique User-Agent/contact string; store it in the NOAA/NWS Weather provider config or NWS_USER_AGENT.',
  },
  {
    id: 'open-meteo-weather-api',
    url: 'https://open-meteo.com/en/docs',
    title: 'Open-Meteo forecast and historical weather APIs',
    category: 'weather-hazards',
    tags: ['spec', 'weather', 'global', 'forecast', 'historical', 'location-aware'],
    credibilityScore: 78,
    relevanceScore: 78,
    requiredFields: ['latitude/longitude', 'forecast timestamp', 'weather variable', 'company location overlap'],
    implementationNotes: 'Use as a no-key global weather supplement when company locations fall outside U.S. NWS coverage. Keep NWS as authoritative for U.S. alerts.',
  },
  {
    id: 'openfema-api',
    url: 'https://www.fema.gov/about/openfema/api',
    title: 'OpenFEMA API and disaster datasets',
    category: 'disasters',
    tags: ['spec', 'disaster', 'fema', 'local-risk', 'infrastructure', 'insurance', 'construction'],
    credibilityScore: 91,
    relevanceScore: 82,
    requiredFields: ['disaster declaration date', 'incident type', 'state/county', 'program/funding amount', 'company location overlap'],
    implementationNotes: 'Use OpenFEMA disaster declarations, public assistance, NFIP, and related datasets to localize disaster exposure and recovery-spend tailwinds. Free and no API key required.',
  },
  {
    id: 'usaspending-api',
    url: 'https://api.usaspending.gov/',
    title: 'USAspending federal awards and contracts API',
    category: 'government-contracts',
    tags: ['spec', 'contracts', 'government-spending', 'defense', 'infrastructure', 'revenue-catalyst'],
    credibilityScore: 92,
    relevanceScore: 86,
    requiredFields: ['award date', 'recipient', 'recipient location', 'agency', 'award amount', 'contract/grant type'],
    implementationNotes: 'Use for federal contract/grant recipients, award amounts, agencies, geography, and defense/infrastructure/government-demand catalysts. Endpoints currently require no authorization.',
  },
  {
    id: 'clinicaltrials-api-v2',
    url: 'https://clinicaltrials.gov/data-api/api',
    title: 'ClinicalTrials.gov API v2',
    category: 'healthcare-catalysts',
    tags: ['spec', 'clinical-trials', 'biotech', 'pharma', 'medical-device', 'catalyst'],
    credibilityScore: 91,
    relevanceScore: 84,
    requiredFields: ['NCT ID', 'sponsor/collaborator', 'phase', 'status', 'condition', 'intervention', 'last update timestamp'],
    implementationNotes: 'Use for healthcare and biotech catalysts, trial phase/status changes, sponsor pipelines, and competitive/product risk. Tie trial evidence to named sponsors, collaborators, and public tickers before scoring.',
  },
  {
    id: 'openfda-api',
    url: 'https://open.fda.gov/apis/',
    title: 'openFDA public FDA APIs',
    category: 'healthcare-consumer-risk',
    tags: ['spec', 'fda', 'recalls', 'adverse-events', 'drug', 'device', 'food', 'regulatory-risk'],
    credibilityScore: 91,
    relevanceScore: 84,
    requiredFields: ['endpoint/category', 'report date', 'manufacturer/brand', 'product', 'recall/adverse-event classification', 'source record ID'],
    implementationNotes: 'Use for drug/device/food recalls, adverse events, labels, NDCs, and historical FDA documents. A free openFDA API key should be configured for production-scale use; no-key access has lower daily limits.',
  },
  {
    id: 'reliefweb-api',
    url: 'https://reliefweb.int/help/api',
    title: 'ReliefWeb disaster and humanitarian reports API',
    category: 'global-disasters-conflict',
    tags: ['spec', 'disaster', 'war', 'humanitarian', 'global', 'location-aware', 'supply-chain'],
    credibilityScore: 84,
    relevanceScore: 80,
    requiredFields: ['report date', 'country/region', 'disaster/conflict type', 'source organization', 'document URL'],
    implementationNotes: 'Use as a global disaster/conflict report source to supplement GDELT and official local feeds. Requests should include the configured ReliefWeb application name.',
  },
  {
    id: 'nhtsa-recalls-api',
    url: 'https://www.nhtsa.gov/nhtsa-datasets-and-apis',
    title: 'NHTSA recalls and vehicle safety datasets/APIs',
    category: 'automotive-regulatory-risk',
    tags: ['spec', 'automotive', 'recalls', 'safety', 'regulatory-risk', 'consumer-products'],
    credibilityScore: 90,
    relevanceScore: 78,
    requiredFields: ['campaign ID', 'manufacturer', 'component', 'report date', 'recall status', 'affected units'],
    implementationNotes: 'Use for auto manufacturers, suppliers, fleet/logistics companies, recall shocks, and product-quality/regulatory risk. Connect manufacturer names to public tickers before scoring.',
  },
  {
    id: 'openalex-api',
    url: 'https://developers.openalex.org/',
    title: 'OpenAlex scholarly research graph and API',
    category: 'technology-research',
    tags: ['spec', 'scholarly', 'technology', 'patents-adjacent', 'r-and-d', 'funders', 'semantic-search'],
    credibilityScore: 86,
    relevanceScore: 78,
    requiredFields: ['work/topic/institution ID', 'publication date', 'author/institution/funder', 'topic/keyword', 'citation/relevance score'],
    implementationNotes: 'Use for R&D, academic momentum, emerging technology, funder/institution networks, and semantic search around products or sectors. The API has a free key tier; configure OpenAlex for normal-scale use.',
  },
];

const SPEC_DISCOVERY_QUERIES = [
  'SEC EDGAR XBRL company facts filings point in time data',
  'official BLS BEA FRED Census macro release timestamp API',
  'Census Business Formation Statistics EIN applications employer business formations startup momentum API',
  'Treasury bill return benchmark official data API',
  'Nasdaq symbol directory listed securities delisting symbol changes',
  'Fama French factor benchmark data library',
  'EIA oil gas energy data API shipping costs investment research',
  'GDELT global news events company organization location tone API investment research',
  'GDELT DOC API business news startup funding IPO acquisition search',
  'Google News RSS business startup funding IPO discovery feed',
  'SEC RSS press releases litigation releases administrative proceedings trading suspensions EDGAR structured disclosure XBRL',
  'FTC DOJ CFPB Federal Reserve regulatory news antitrust fraud consumer finance monetary policy RSS',
  'FDA press announcements drug approval device decision recalls safety warning company catalyst',
  'Department of Defense contracts daily awards contractor ticker revenue catalyst',
  'NOAA NWS active weather alerts company facilities supply chain risk API',
  'OpenFEMA disaster declarations public assistance funded projects economic impact API',
  'USAspending federal awards contracts company recipient defense infrastructure API',
  'ClinicalTrials.gov API sponsor biotech pharma catalyst phase status',
  'openFDA recalls adverse events device drug food regulatory risk API',
  'ReliefWeb API disaster conflict humanitarian reports supply chain companies',
  'NHTSA recalls API manufacturer component affected units investor risk',
  'OpenAlex semantic search technology research funders institutions company innovation',
];

const SPEC_RELEVANCE_TERMS = [
  'filing',
  'edgar',
  'xbrl',
  'companyfacts',
  'acceptance',
  'publication',
  'revision',
  'vintage',
  'benchmark',
  'treasury',
  't-bill',
  'factor',
  'symbol',
  'listed',
  'delisting',
  'dividend',
  'split',
  'macro release',
  'economic indicator',
  'business formation',
  'business applications',
  'ein applications',
  'employer business formations',
  'startup formation',
  'retail sales',
  'energy',
  'oil',
  'gas',
  'gdelt',
  'doc api',
  'global news',
  'business news',
  'google news',
  'rss',
  'startup funding',
  'ipo',
  'acquisition',
  'press release',
  'litigation release',
  'administrative proceeding',
  'trading suspension',
  'structured disclosure',
  'regulatory',
  'antitrust',
  'fraud',
  'consumer protection',
  'consumer finance',
  'monetary policy',
  'organization',
  'tone',
  'sentiment',
  'weather',
  'forecast',
  'alert',
  'disaster',
  'fema',
  'reliefweb',
  'conflict',
  'war',
  'humanitarian',
  'contract',
  'award',
  'defense contract',
  'federal spending',
  'defense',
  'clinical trial',
  'sponsor',
  'phase 3',
  'fda',
  'recall',
  'adverse event',
  'nhtsa',
  'manufacturer',
  'openalex',
  'scholarly',
  'semantic search',
];

function toResearchSeedSources() {
  return SPEC_DATA_SOURCE_CATALOG.map((source) => ({
    url: source.url,
    title: source.title,
    tags: source.tags,
    credibilityScore: source.credibilityScore,
    relevanceScore: source.relevanceScore,
    notes: `${source.category}: ${source.implementationNotes} Required SPEC fields: ${source.requiredFields.join(', ')}.`,
  }));
}

module.exports = {
  SPEC_IMPLEMENTATION_NOTE,
  SPEC_DATA_SOURCE_CATALOG,
  SPEC_DISCOVERY_QUERIES,
  SPEC_RELEVANCE_TERMS,
  toResearchSeedSources,
};
