const SPEC_IMPLEMENTATION_NOTE = [
  'Do not invent APIs, data fields, or library behavior.',
  'Consult official documentation before implementing an external integration.',
  'When source behavior is uncertain, isolate it behind an interface, add tests, and avoid silent assumptions.',
].join(' ');

const SPEC_DATA_SOURCE_CATALOG = [
  {
    id: 'sec-edgar-submissions',
    url: 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces',
    title: 'SEC EDGAR submissions and XBRL APIs',
    category: 'filings',
    tags: ['spec', 'sec', 'edgar', 'filings', 'xbrl', 'fundamentals', 'point-in-time'],
    credibilityScore: 96,
    relevanceScore: 92,
    requiredFields: ['SEC filing acceptance timestamp', 'fundamental reporting period', 'fundamental publication timestamp', 'revision version'],
    implementationNotes: 'Use official SEC documentation and fair-access guidance before adding any adapter. Store raw submissions/XBRL immutably before normalized fundamentals.',
  },
  {
    id: 'sec-data-api',
    url: 'https://data.sec.gov/',
    title: 'SEC data.sec.gov API landing page',
    category: 'filings',
    tags: ['spec', 'sec', 'companyfacts', 'submissions', 'xbrl', 'raw-source'],
    credibilityScore: 96,
    relevanceScore: 90,
    requiredFields: ['SEC filing acceptance timestamp', 'data source', 'ingestion timestamp'],
    implementationNotes: 'Official JSON endpoints for submissions and extracted XBRL. Adapter must provide a descriptive User-Agent and rate-limit per SEC fair-access policy.',
  },
  {
    id: 'nasdaq-symbol-directory',
    url: 'https://www.nasdaqtrader.com/trader.aspx?id=symboldirdefs',
    title: 'Nasdaq Trader Symbol Directory definitions',
    category: 'security-master',
    tags: ['spec', 'universe', 'symbol-directory', 'listing', 'etf', 'security-master'],
    credibilityScore: 88,
    relevanceScore: 86,
    requiredFields: ['symbol', 'exchange', 'security type', 'listing status'],
    implementationNotes: 'Use as a curated security-master seed only. Historical universes still need PIT snapshots and delisting retention.',
  },
  {
    id: 'nasdaq-listed-symbols',
    url: 'https://www.nasdaqtrader.com/dynamic/symdir/nasdaqlisted.txt',
    title: 'Nasdaq-listed securities text file',
    category: 'security-master',
    tags: ['spec', 'universe', 'nasdaq-listed', 'listing', 'security-master'],
    credibilityScore: 86,
    relevanceScore: 84,
    requiredFields: ['symbol', 'security name', 'ETF flag', 'test issue flag'],
    implementationNotes: 'Use only through a tested parser. Do not treat current symbol lists as historical universe membership.',
  },
  {
    id: 'bls-api',
    url: 'https://www.bls.gov/bls/api_features.htm',
    title: 'BLS Public Data API',
    category: 'macro',
    tags: ['spec', 'macro', 'labor', 'inflation', 'release-timestamp', 'data-api'],
    credibilityScore: 92,
    relevanceScore: 86,
    requiredFields: ['macro release timestamp', 'data source', 'revision version'],
    implementationNotes: 'Use BLS official API signatures for CPI, employment, wages, and labor data. Preserve publication/release timestamps when available.',
  },
  {
    id: 'bea-api',
    url: 'https://www.bea.gov/resources/for-developers',
    title: 'BEA developer resources and API',
    category: 'macro',
    tags: ['spec', 'macro', 'gdp', 'income', 'consumer', 'bea-api'],
    credibilityScore: 92,
    relevanceScore: 86,
    requiredFields: ['macro release timestamp', 'revision version', 'data source'],
    implementationNotes: 'Use official BEA metadata endpoints before mapping datasets. BEA API keys must remain in credentials/config only.',
  },
  {
    id: 'fred-alfred-api',
    url: 'https://fred.stlouisfed.org/docs/api/fred/',
    title: 'FRED and ALFRED API documentation',
    category: 'macro',
    tags: ['spec', 'macro', 'alfred', 'fred', 'vintages', 'rates', 'point-in-time'],
    credibilityScore: 94,
    relevanceScore: 90,
    requiredFields: ['macro release timestamp', 'revision version', 'data source'],
    implementationNotes: 'Prefer ALFRED vintages for point-in-time macro where possible. Do not use revised FRED values as if they were available historically.',
  },
  {
    id: 'federal-reserve-h15',
    url: 'https://www.federalreserve.gov/releases/h15/',
    title: 'Federal Reserve H.15 Selected Interest Rates',
    category: 'rates',
    tags: ['spec', 'treasury', 'rates', 'yield-curve', 'benchmark', 'h15'],
    credibilityScore: 93,
    relevanceScore: 86,
    requiredFields: ['macro release timestamp', 'Treasury-bill return', 'yield-curve slope'],
    implementationNotes: 'Use the Federal Reserve Data Download Program or FRED/ALFRED vintages; preserve release dates and avoid look-ahead revised data.',
  },
  {
    id: 'treasury-fiscaldata-api',
    url: 'https://fiscaldata.treasury.gov/api-documentation/',
    title: 'U.S. Treasury FiscalData API documentation',
    category: 'rates',
    tags: ['spec', 'treasury', 'fiscaldata', 't-bill', 'cash-benchmark'],
    credibilityScore: 92,
    relevanceScore: 84,
    requiredFields: ['Treasury-bill return', 'data source', 'ingestion timestamp'],
    implementationNotes: 'Use official FiscalData APIs for Treasury datasets and cash/rate benchmark support.',
  },
  {
    id: 'census-economic-indicators',
    url: 'https://www.census.gov/data/developers/data-sets/economic-indicators.html',
    title: 'Census Economic Indicators API datasets',
    category: 'consumer',
    tags: ['spec', 'consumer', 'retail-sales', 'economic-indicators', 'census-api'],
    credibilityScore: 90,
    relevanceScore: 84,
    requiredFields: ['macro release timestamp', 'consumer sales reports', 'revision version'],
    implementationNotes: 'Use official Census API guidance for retail, trade, housing, and manufacturing indicator time series.',
  },
  {
    id: 'eia-open-data',
    url: 'https://www.eia.gov/opendata/documentation.php',
    title: 'EIA Open Data API documentation',
    category: 'commodities',
    tags: ['spec', 'energy', 'oil', 'gas', 'commodities', 'shipping-costs'],
    credibilityScore: 90,
    relevanceScore: 84,
    requiredFields: ['commodity trend', 'macro release timestamp', 'data source'],
    implementationNotes: 'Use official EIA Open Data endpoints for oil/gas/electricity inputs that affect energy, logistics, and shipping-cost evaluation.',
  },
  {
    id: 'fama-french-data-library',
    url: 'https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html',
    title: 'Kenneth French Data Library',
    category: 'factor-benchmark',
    tags: ['spec', 'factor-benchmark', 'market-factor', 'size', 'value', 'momentum'],
    credibilityScore: 88,
    relevanceScore: 82,
    requiredFields: ['relevant factor benchmarks', 'benchmark performance', 'data source'],
    implementationNotes: 'Use as benchmark/factor reference data, not as a security-master replacement. Record exact file vintage when ingested.',
  },
  {
    id: 'world-bank-open-data',
    url: 'https://data.worldbank.org/',
    title: 'World Bank Open Data',
    category: 'global-macro',
    tags: ['spec', 'global', 'population', 'gdp', 'macro', 'demand'],
    credibilityScore: 88,
    relevanceScore: 80,
    requiredFields: ['population data', 'GDP trend', 'data source'],
    implementationNotes: 'Use for global demand/population/GDP context. Keep publication/available-at assumptions explicit in adapter tests.',
  },
  {
    id: 'news-source-ratings',
    url: 'https://yougov.com/en-us/ratings/news-websites',
    title: 'YouGov news website ratings seed',
    category: 'news-source-quality',
    tags: ['spec', 'news', 'source-quality', 'text-derived', 'low-confidence-social'],
    credibilityScore: 62,
    relevanceScore: 66,
    requiredFields: ['document references', 'citations', 'source quality'],
    implementationNotes: 'Use only for discovery/source-quality context. Text claims still require document citations and prompt-injection screening.',
  },
  {
    id: 'gdelt-global-news-events',
    url: 'https://www.gdeltproject.org/',
    title: 'GDELT global news, events, locations, organizations, and tone',
    category: 'global-news-events',
    tags: ['spec', 'news', 'events', 'war', 'geopolitics', 'location-aware', 'sentiment', 'organizations'],
    credibilityScore: 82,
    relevanceScore: 90,
    requiredFields: ['event timestamp', 'article/document reference', 'location', 'organization/entity', 'tone/sentiment', 'source language'],
    implementationNotes: 'Use GDELT DOC/GEO/Event/GKG APIs as global, near-real-time context for war, civil unrest, local demand, supply-chain disruption, organization mentions, and narrative tone. Treat it as text/event evidence that must be tied to company geography before changing scores.',
  },
  {
    id: 'noaa-nws-api',
    url: 'https://www.weather.gov/documentation/services-web-api',
    title: 'NOAA/National Weather Service API',
    category: 'weather-hazards',
    tags: ['spec', 'weather', 'alerts', 'local-risk', 'supply-chain', 'retail-footprint', 'location-aware'],
    credibilityScore: 93,
    relevanceScore: 82,
    requiredFields: ['alert effective timestamp', 'alert area', 'severity', 'certainty', 'urgency', 'company location overlap'],
    implementationNotes: 'Use for U.S. weather alerts, forecasts, observations, and localized operational risk. Official requests require a unique User-Agent/contact string; store it in the NOAA/NWS Weather provider config or NWS_USER_AGENT.',
  },
  {
    id: 'open-meteo-weather-api',
    url: 'https://open-meteo.com/en/docs',
    title: 'Open-Meteo forecast and historical weather APIs',
    category: 'weather-hazards',
    tags: ['spec', 'weather', 'global', 'forecast', 'historical', 'location-aware'],
    credibilityScore: 78,
    relevanceScore: 78,
    requiredFields: ['latitude/longitude', 'forecast timestamp', 'weather variable', 'company location overlap'],
    implementationNotes: 'Use as a no-key global weather supplement when company locations fall outside U.S. NWS coverage. Keep NWS as authoritative for U.S. alerts.',
  },
  {
    id: 'openfema-api',
    url: 'https://www.fema.gov/about/openfema/api',
    title: 'OpenFEMA API and disaster datasets',
    category: 'disasters',
    tags: ['spec', 'disaster', 'fema', 'local-risk', 'infrastructure', 'insurance', 'construction'],
    credibilityScore: 91,
    relevanceScore: 82,
    requiredFields: ['disaster declaration date', 'incident type', 'state/county', 'program/funding amount', 'company location overlap'],
    implementationNotes: 'Use OpenFEMA disaster declarations, public assistance, NFIP, and related datasets to localize disaster exposure and recovery-spend tailwinds. Free and no API key required.',
  },
  {
    id: 'usaspending-api',
    url: 'https://api.usaspending.gov/',
    title: 'USAspending federal awards and contracts API',
    category: 'government-contracts',
    tags: ['spec', 'contracts', 'government-spending', 'defense', 'infrastructure', 'revenue-catalyst'],
    credibilityScore: 92,
    relevanceScore: 86,
    requiredFields: ['award date', 'recipient', 'recipient location', 'agency', 'award amount', 'contract/grant type'],
    implementationNotes: 'Use for federal contract/grant recipients, award amounts, agencies, geography, and defense/infrastructure/government-demand catalysts. Endpoints currently require no authorization.',
  },
  {
    id: 'clinicaltrials-api-v2',
    url: 'https://clinicaltrials.gov/data-api/api',
    title: 'ClinicalTrials.gov API v2',
    category: 'healthcare-catalysts',
    tags: ['spec', 'clinical-trials', 'biotech', 'pharma', 'medical-device', 'catalyst'],
    credibilityScore: 91,
    relevanceScore: 84,
    requiredFields: ['NCT ID', 'sponsor/collaborator', 'phase', 'status', 'condition', 'intervention', 'last update timestamp'],
    implementationNotes: 'Use for healthcare and biotech catalysts, trial phase/status changes, sponsor pipelines, and competitive/product risk. Tie trial evidence to named sponsors, collaborators, and public tickers before scoring.',
  },
  {
    id: 'openfda-api',
    url: 'https://open.fda.gov/apis/',
    title: 'openFDA public FDA APIs',
    category: 'healthcare-consumer-risk',
    tags: ['spec', 'fda', 'recalls', 'adverse-events', 'drug', 'device', 'food', 'regulatory-risk'],
    credibilityScore: 91,
    relevanceScore: 84,
    requiredFields: ['endpoint/category', 'report date', 'manufacturer/brand', 'product', 'recall/adverse-event classification', 'source record ID'],
    implementationNotes: 'Use for drug/device/food recalls, adverse events, labels, NDCs, and historical FDA documents. A free openFDA API key should be configured for production-scale use; no-key access has lower daily limits.',
  },
  {
    id: 'reliefweb-api',
    url: 'https://reliefweb.int/help/api',
    title: 'ReliefWeb disaster and humanitarian reports API',
    category: 'global-disasters-conflict',
    tags: ['spec', 'disaster', 'war', 'humanitarian', 'global', 'location-aware', 'supply-chain'],
    credibilityScore: 84,
    relevanceScore: 80,
    requiredFields: ['report date', 'country/region', 'disaster/conflict type', 'source organization', 'document URL'],
    implementationNotes: 'Use as a global disaster/conflict report source to supplement GDELT and official local feeds. Requests should include the configured ReliefWeb application name.',
  },
  {
    id: 'nhtsa-recalls-api',
    url: 'https://www.nhtsa.gov/nhtsa-datasets-and-apis',
    title: 'NHTSA recalls and vehicle safety datasets/APIs',
    category: 'automotive-regulatory-risk',
    tags: ['spec', 'automotive', 'recalls', 'safety', 'regulatory-risk', 'consumer-products'],
    credibilityScore: 90,
    relevanceScore: 78,
    requiredFields: ['campaign ID', 'manufacturer', 'component', 'report date', 'recall status', 'affected units'],
    implementationNotes: 'Use for auto manufacturers, suppliers, fleet/logistics companies, recall shocks, and product-quality/regulatory risk. Connect manufacturer names to public tickers before scoring.',
  },
  {
    id: 'openalex-api',
    url: 'https://developers.openalex.org/',
    title: 'OpenAlex scholarly research graph and API',
    category: 'technology-research',
    tags: ['spec', 'scholarly', 'technology', 'patents-adjacent', 'r-and-d', 'funders', 'semantic-search'],
    credibilityScore: 86,
    relevanceScore: 78,
    requiredFields: ['work/topic/institution ID', 'publication date', 'author/institution/funder', 'topic/keyword', 'citation/relevance score'],
    implementationNotes: 'Use for R&D, academic momentum, emerging technology, funder/institution networks, and semantic search around products or sectors. The API has a free key tier; configure OpenAlex for normal-scale use.',
  },
];

const SPEC_DISCOVERY_QUERIES = [
  'SEC EDGAR XBRL company facts filings point in time data',
  'official BLS BEA FRED Census macro release timestamp API',
  'Treasury bill return benchmark official data API',
  'Nasdaq symbol directory listed securities delisting symbol changes',
  'Fama French factor benchmark data library',
  'EIA oil gas energy data API shipping costs investment research',
  'GDELT global news events company organization location tone API investment research',
  'NOAA NWS active weather alerts company facilities supply chain risk API',
  'OpenFEMA disaster declarations public assistance funded projects economic impact API',
  'USAspending federal awards contracts company recipient defense infrastructure API',
  'ClinicalTrials.gov API sponsor biotech pharma catalyst phase status',
  'openFDA recalls adverse events device drug food regulatory risk API',
  'ReliefWeb API disaster conflict humanitarian reports supply chain companies',
  'NHTSA recalls API manufacturer component affected units investor risk',
  'OpenAlex semantic search technology research funders institutions company innovation',
];

const SPEC_RELEVANCE_TERMS = [
  'filing',
  'edgar',
  'xbrl',
  'companyfacts',
  'acceptance',
  'publication',
  'revision',
  'vintage',
  'benchmark',
  'treasury',
  't-bill',
  'factor',
  'symbol',
  'listed',
  'delisting',
  'dividend',
  'split',
  'macro release',
  'economic indicator',
  'retail sales',
  'energy',
  'oil',
  'gas',
  'gdelt',
  'global news',
  'organization',
  'tone',
  'sentiment',
  'weather',
  'forecast',
  'alert',
  'disaster',
  'fema',
  'reliefweb',
  'conflict',
  'war',
  'humanitarian',
  'contract',
  'award',
  'federal spending',
  'defense',
  'clinical trial',
  'sponsor',
  'phase 3',
  'fda',
  'recall',
  'adverse event',
  'nhtsa',
  'manufacturer',
  'openalex',
  'scholarly',
  'semantic search',
];

function toResearchSeedSources() {
  return SPEC_DATA_SOURCE_CATALOG.map((source) => ({
    url: source.url,
    title: source.title,
    tags: source.tags,
    credibilityScore: source.credibilityScore,
    relevanceScore: source.relevanceScore,
    notes: `${source.category}: ${source.implementationNotes} Required SPEC fields: ${source.requiredFields.join(', ')}.`,
  }));
}

module.exports = {
  SPEC_IMPLEMENTATION_NOTE,
  SPEC_DATA_SOURCE_CATALOG,
  SPEC_DISCOVERY_QUERIES,
  SPEC_RELEVANCE_TERMS,
  toResearchSeedSources,
};
